version: "2"
services:
 database:
    image: postgres:latest
    ports:
     - 5411:5432
    volumes:
     - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Eh7gLagHHHzK2h7j
      POSTGRES_USER: portfolio
      POSTGRES_DB: portfolio
 mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/var/lib/monodb/data
    environment:
        MONGODB_USER: portoflio
        MONGODB_PASS: Eh7gLagHHHzK2h7j
        MONGODB_DATABASE: portoflio
    command: mongod --smallfiles --logpath=/dev/null # --quiet
volumes:
 data: {}
